# Generated by Django 4.2.17 on 2024-12-16 10:57

from django.db import migrations
import django_measurement.models
import measurement.measures.volume


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='available_quantity',
            field=django_measurement.models.MeasurementField(measurement=measurement.measures.volume.Volume),
        ),
    ]
