# Generated by Django 4.2.17 on 2024-12-21 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_ingredient_price_per_unit_currency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='price_per_unit',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='price_per_unit_currency',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='unit_of_measurement',
            field=models.CharField(default='grams', max_length=100),
        ),
    ]
