# Generated by Django 4.2.17 on 2024-12-26 23:03

from django.db import migrations
import django_jsonform.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_menuitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='recipeRequirements',
            field=django_jsonform.models.fields.JSONField(default=list),
        ),
    ]
