# Generated by Django 4.2.17 on 2024-12-26 23:04

from django.db import migrations
import django_jsonform.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_menuitem_reciperequirements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='recipeRequirements',
            field=django_jsonform.models.fields.JSONField(),
        ),
    ]
